services:

  postgres:
    image: postgres:16-alpine
    container_name: core-postgres
    env_file:
      .env
    environment:
      POSTGRES_DB: routecraft_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U routecraft -d routecraft"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: core-redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "redis"
    ]

  minio:
    image: minio/minio
    container_name: core-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:5173,http://127.0.0.1:5173
      MINIO_NOTIFY_WEBHOOK_ENABLE_myapp: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_myapp: http://host.docker.internal:8081/webhooks/minio
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_myapp: "secret_key"
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set myminio http://minio:9000 minio minioadmin; do
        echo 'Ожидание запуска MinIO...';
        sleep 2;
      done;
      mc mb myminio/routes --ignore-existing;
      mc event add myminio/routes arn:minio:sqs::myapp:webhook --event put;
      echo 'MinIO успешно настроен!';
      exit 0;
      "

volumes:
  postgres_data:
  redis_data:
  minio_data:
