--liquibase formatted sql

--changeset kemalthes:1

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(32) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name),
    CONSTRAINT chk_roles_name CHECK (name IN ('USER', 'ADMIN'))
);

CREATE TABLE users (
    id UUID NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_roles (
    user_id UUID NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE tour_routes (
    id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    base_price INTEGER NOT NULL,
    distance NUMERIC(12, 3),
    duration_minutes INTEGER,
    author_id UUID NOT NULL,
    CONSTRAINT pk_tour_routes PRIMARY KEY (id),
    CONSTRAINT fk_tour_routes_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE locations (
    id UUID NOT NULL,
    route_id UUID NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    order_index INTEGER NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id),
    CONSTRAINT uk_locations_route_order UNIQUE (route_id, order_index),
    CONSTRAINT fk_locations_route FOREIGN KEY (route_id) REFERENCES tour_routes (id) ON DELETE CASCADE
);

CREATE TABLE favorites (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    route_id UUID NOT NULL,
    CONSTRAINT pk_favorites PRIMARY KEY (id),
    CONSTRAINT uk_favorites_user_route UNIQUE (user_id, route_id),
    CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_route FOREIGN KEY (route_id) REFERENCES tour_routes (id) ON DELETE CASCADE
);

CREATE TABLE reviews (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    route_id UUID NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT,
    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_route FOREIGN KEY (route_id) REFERENCES tour_routes (id) ON DELETE CASCADE
);