spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:15432/routecraft_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true

  data:
    redis:
      host: localhost
      port: 16379
      password: redis

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          connectionTimeout: 5000
          timeout: 5000
          writeTimeout: 5000
          ssl:
            enable: true
          starttls:
            enable: false

minio:
  endpoint: http://localhost:9000
  accessKey: minio
  secretKey: minioadmin
  bucket: routes
  webhook-token: "secret_key"
  presignedUrlTtl: 10

allowed-origin-patterns: http://localhost,http://localhost:*,http://127.0.0.1,http://127.0.0.1:*
